version: '3.1'
services:
  db:
    container_name: db_pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - backend
networks:
  backend:
    driver: bridge
  # db:
  #   image: mongo
  #   restart: on-failure
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo
  #     MONGO_INITDB_ROOT_PASSWORD: mongo
  #     MONGO_INITDB_DATABASE: music_room
  #   ports:
  #     - "27017:27017"